# Generated by Django 3.1.4 on 2020-12-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20190526_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '컨텐츠'},
        ),
    ]
